name: enigma-github-actions
on: [push]
jobs: 
  test_enigma:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./enigma
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      -name: Checkout the repo 
       uses: actions/checkout@v2
      -name: install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install pytest
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      -name: Run tests
       run: |
       pip install pytest
       pip install pytest-cov
       pytest test_enigma.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
      -name: Upload pytest test results
       uses: actions/upload-artifact@v2
       with:
         name: pytest-results
         path: ./enigma/junit/test-results.xml
         # Use always() to always run this step to publish test results when there are test failures
       if: ${{ always() }}
    
