name: enigma-github-actions
on: [push]
jobs: 
  test_enigma:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./enigma
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.5'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests
        run: |
          pip install pytest
          pytest test_enigma.py
